// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/entrustsecond/entrustsecond.proto

package go_micro_api_entrust

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Pair struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values               []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pair) Reset()         { *m = Pair{} }
func (m *Pair) String() string { return proto.CompactTextString(m) }
func (*Pair) ProtoMessage()    {}
func (*Pair) Descriptor() ([]byte, []int) {
	return fileDescriptor_de98e18bbaa1ad4f, []int{0}
}

func (m *Pair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pair.Unmarshal(m, b)
}
func (m *Pair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pair.Marshal(b, m, deterministic)
}
func (m *Pair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pair.Merge(m, src)
}
func (m *Pair) XXX_Size() int {
	return xxx_messageInfo_Pair.Size(m)
}
func (m *Pair) XXX_DiscardUnknown() {
	xxx_messageInfo_Pair.DiscardUnknown(m)
}

var xxx_messageInfo_Pair proto.InternalMessageInfo

func (m *Pair) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Pair) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type Request struct {
	Method               string           `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path                 string           `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Header               map[string]*Pair `protobuf:"bytes,3,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Get                  map[string]*Pair `protobuf:"bytes,4,rep,name=get,proto3" json:"get,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Post                 map[string]*Pair `protobuf:"bytes,5,rep,name=post,proto3" json:"post,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 string           `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	Url                  string           `protobuf:"bytes,7,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_de98e18bbaa1ad4f, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Request) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Request) GetHeader() map[string]*Pair {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Request) GetGet() map[string]*Pair {
	if m != nil {
		return m.Get
	}
	return nil
}

func (m *Request) GetPost() map[string]*Pair {
	if m != nil {
		return m.Post
	}
	return nil
}

func (m *Request) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Request) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type Response struct {
	StatusCode           int32            `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Header               map[string]*Pair `protobuf:"bytes,2,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 string           `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_de98e18bbaa1ad4f, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *Response) GetHeader() map[string]*Pair {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Response) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type TradeRequest struct {
	CurrencyId           int32    `protobuf:"varint,1,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	CurrencyTradeId      int32    `protobuf:"varint,2,opt,name=currency_trade_id,json=currencyTradeId,proto3" json:"currency_trade_id,omitempty"`
	Num                  float64  `protobuf:"fixed64,3,opt,name=num,proto3" json:"num,omitempty"`
	Price                float64  `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TradeRequest) Reset()         { *m = TradeRequest{} }
func (m *TradeRequest) String() string { return proto.CompactTextString(m) }
func (*TradeRequest) ProtoMessage()    {}
func (*TradeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_de98e18bbaa1ad4f, []int{3}
}

func (m *TradeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TradeRequest.Unmarshal(m, b)
}
func (m *TradeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TradeRequest.Marshal(b, m, deterministic)
}
func (m *TradeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradeRequest.Merge(m, src)
}
func (m *TradeRequest) XXX_Size() int {
	return xxx_messageInfo_TradeRequest.Size(m)
}
func (m *TradeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TradeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TradeRequest proto.InternalMessageInfo

func (m *TradeRequest) GetCurrencyId() int32 {
	if m != nil {
		return m.CurrencyId
	}
	return 0
}

func (m *TradeRequest) GetCurrencyTradeId() int32 {
	if m != nil {
		return m.CurrencyTradeId
	}
	return 0
}

func (m *TradeRequest) GetNum() float64 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *TradeRequest) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type TradeOrderResponse struct {
	Orders               []*TradeOrder `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TradeOrderResponse) Reset()         { *m = TradeOrderResponse{} }
func (m *TradeOrderResponse) String() string { return proto.CompactTextString(m) }
func (*TradeOrderResponse) ProtoMessage()    {}
func (*TradeOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_de98e18bbaa1ad4f, []int{4}
}

func (m *TradeOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TradeOrderResponse.Unmarshal(m, b)
}
func (m *TradeOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TradeOrderResponse.Marshal(b, m, deterministic)
}
func (m *TradeOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradeOrderResponse.Merge(m, src)
}
func (m *TradeOrderResponse) XXX_Size() int {
	return xxx_messageInfo_TradeOrderResponse.Size(m)
}
func (m *TradeOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TradeOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TradeOrderResponse proto.InternalMessageInfo

func (m *TradeOrderResponse) GetOrders() []*TradeOrder {
	if m != nil {
		return m.Orders
	}
	return nil
}

type TradeOrder struct {
	OrdersId             int32    `protobuf:"varint,1,opt,name=orders_id,json=ordersId,proto3" json:"orders_id,omitempty"`
	CustomerId           int32    `protobuf:"varint,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	CurrencyId           int32    `protobuf:"varint,3,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	CurrencyTradeId      int32    `protobuf:"varint,4,opt,name=currency_trade_id,json=currencyTradeId,proto3" json:"currency_trade_id,omitempty"`
	Price                float64  `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Num                  float64  `protobuf:"fixed64,6,opt,name=num,proto3" json:"num,omitempty"`
	TradeNum             float64  `protobuf:"fixed64,7,opt,name=trade_num,json=tradeNum,proto3" json:"trade_num,omitempty"`
	Fee                  float64  `protobuf:"fixed64,8,opt,name=fee,proto3" json:"fee,omitempty"`
	Type                 string   `protobuf:"bytes,9,opt,name=type,proto3" json:"type,omitempty"`
	AddTime              string   `protobuf:"bytes,10,opt,name=add_time,json=addTime,proto3" json:"add_time,omitempty"`
	TradeTime            string   `protobuf:"bytes,11,opt,name=trade_time,json=tradeTime,proto3" json:"trade_time,omitempty"`
	Status               int32    `protobuf:"varint,12,opt,name=status,proto3" json:"status,omitempty"`
	CurrencyMark         string   `protobuf:"bytes,13,opt,name=currency_mark,json=currencyMark,proto3" json:"currency_mark,omitempty"`
	CurrencyTradeMark    string   `protobuf:"bytes,14,opt,name=currency_trade_mark,json=currencyTradeMark,proto3" json:"currency_trade_mark,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TradeOrder) Reset()         { *m = TradeOrder{} }
func (m *TradeOrder) String() string { return proto.CompactTextString(m) }
func (*TradeOrder) ProtoMessage()    {}
func (*TradeOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_de98e18bbaa1ad4f, []int{5}
}

func (m *TradeOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TradeOrder.Unmarshal(m, b)
}
func (m *TradeOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TradeOrder.Marshal(b, m, deterministic)
}
func (m *TradeOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradeOrder.Merge(m, src)
}
func (m *TradeOrder) XXX_Size() int {
	return xxx_messageInfo_TradeOrder.Size(m)
}
func (m *TradeOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_TradeOrder.DiscardUnknown(m)
}

var xxx_messageInfo_TradeOrder proto.InternalMessageInfo

func (m *TradeOrder) GetOrdersId() int32 {
	if m != nil {
		return m.OrdersId
	}
	return 0
}

func (m *TradeOrder) GetCustomerId() int32 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *TradeOrder) GetCurrencyId() int32 {
	if m != nil {
		return m.CurrencyId
	}
	return 0
}

func (m *TradeOrder) GetCurrencyTradeId() int32 {
	if m != nil {
		return m.CurrencyTradeId
	}
	return 0
}

func (m *TradeOrder) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *TradeOrder) GetNum() float64 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *TradeOrder) GetTradeNum() float64 {
	if m != nil {
		return m.TradeNum
	}
	return 0
}

func (m *TradeOrder) GetFee() float64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *TradeOrder) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TradeOrder) GetAddTime() string {
	if m != nil {
		return m.AddTime
	}
	return ""
}

func (m *TradeOrder) GetTradeTime() string {
	if m != nil {
		return m.TradeTime
	}
	return ""
}

func (m *TradeOrder) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *TradeOrder) GetCurrencyMark() string {
	if m != nil {
		return m.CurrencyMark
	}
	return ""
}

func (m *TradeOrder) GetCurrencyTradeMark() string {
	if m != nil {
		return m.CurrencyTradeMark
	}
	return ""
}

type UnfinishedRequest struct {
	CurrencyMark         string   `protobuf:"bytes,1,opt,name=currency_mark,json=currencyMark,proto3" json:"currency_mark,omitempty"`
	CurrencyTradeMark    string   `protobuf:"bytes,2,opt,name=currency_trade_mark,json=currencyTradeMark,proto3" json:"currency_trade_mark,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnfinishedRequest) Reset()         { *m = UnfinishedRequest{} }
func (m *UnfinishedRequest) String() string { return proto.CompactTextString(m) }
func (*UnfinishedRequest) ProtoMessage()    {}
func (*UnfinishedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_de98e18bbaa1ad4f, []int{6}
}

func (m *UnfinishedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnfinishedRequest.Unmarshal(m, b)
}
func (m *UnfinishedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnfinishedRequest.Marshal(b, m, deterministic)
}
func (m *UnfinishedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnfinishedRequest.Merge(m, src)
}
func (m *UnfinishedRequest) XXX_Size() int {
	return xxx_messageInfo_UnfinishedRequest.Size(m)
}
func (m *UnfinishedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnfinishedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnfinishedRequest proto.InternalMessageInfo

func (m *UnfinishedRequest) GetCurrencyMark() string {
	if m != nil {
		return m.CurrencyMark
	}
	return ""
}

func (m *UnfinishedRequest) GetCurrencyTradeMark() string {
	if m != nil {
		return m.CurrencyTradeMark
	}
	return ""
}

func (m *UnfinishedRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *UnfinishedRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type BusinessRequest struct {
	CurrencyMark         string   `protobuf:"bytes,1,opt,name=currency_mark,json=currencyMark,proto3" json:"currency_mark,omitempty"`
	CurrencyTradeMark    string   `protobuf:"bytes,2,opt,name=currency_trade_mark,json=currencyTradeMark,proto3" json:"currency_trade_mark,omitempty"`
	Num                  float64  `protobuf:"fixed64,3,opt,name=num,proto3" json:"num,omitempty"`
	Price                float64  `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BusinessRequest) Reset()         { *m = BusinessRequest{} }
func (m *BusinessRequest) String() string { return proto.CompactTextString(m) }
func (*BusinessRequest) ProtoMessage()    {}
func (*BusinessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_de98e18bbaa1ad4f, []int{7}
}

func (m *BusinessRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BusinessRequest.Unmarshal(m, b)
}
func (m *BusinessRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BusinessRequest.Marshal(b, m, deterministic)
}
func (m *BusinessRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BusinessRequest.Merge(m, src)
}
func (m *BusinessRequest) XXX_Size() int {
	return xxx_messageInfo_BusinessRequest.Size(m)
}
func (m *BusinessRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BusinessRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BusinessRequest proto.InternalMessageInfo

func (m *BusinessRequest) GetCurrencyMark() string {
	if m != nil {
		return m.CurrencyMark
	}
	return ""
}

func (m *BusinessRequest) GetCurrencyTradeMark() string {
	if m != nil {
		return m.CurrencyTradeMark
	}
	return ""
}

func (m *BusinessRequest) GetNum() float64 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *BusinessRequest) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type CurrencyEntrustRequest struct {
	CurrencyMark         string   `protobuf:"bytes,1,opt,name=currency_mark,json=currencyMark,proto3" json:"currency_mark,omitempty"`
	CurrencyTradeMark    string   `protobuf:"bytes,2,opt,name=currency_trade_mark,json=currencyTradeMark,proto3" json:"currency_trade_mark,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32    `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Status               int32    `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CurrencyEntrustRequest) Reset()         { *m = CurrencyEntrustRequest{} }
func (m *CurrencyEntrustRequest) String() string { return proto.CompactTextString(m) }
func (*CurrencyEntrustRequest) ProtoMessage()    {}
func (*CurrencyEntrustRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_de98e18bbaa1ad4f, []int{8}
}

func (m *CurrencyEntrustRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrencyEntrustRequest.Unmarshal(m, b)
}
func (m *CurrencyEntrustRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrencyEntrustRequest.Marshal(b, m, deterministic)
}
func (m *CurrencyEntrustRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrencyEntrustRequest.Merge(m, src)
}
func (m *CurrencyEntrustRequest) XXX_Size() int {
	return xxx_messageInfo_CurrencyEntrustRequest.Size(m)
}
func (m *CurrencyEntrustRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrencyEntrustRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CurrencyEntrustRequest proto.InternalMessageInfo

func (m *CurrencyEntrustRequest) GetCurrencyMark() string {
	if m != nil {
		return m.CurrencyMark
	}
	return ""
}

func (m *CurrencyEntrustRequest) GetCurrencyTradeMark() string {
	if m != nil {
		return m.CurrencyTradeMark
	}
	return ""
}

func (m *CurrencyEntrustRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *CurrencyEntrustRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *CurrencyEntrustRequest) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type CancelRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderNo              string   `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelRequest) Reset()         { *m = CancelRequest{} }
func (m *CancelRequest) String() string { return proto.CompactTextString(m) }
func (*CancelRequest) ProtoMessage()    {}
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_de98e18bbaa1ad4f, []int{9}
}

func (m *CancelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelRequest.Unmarshal(m, b)
}
func (m *CancelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelRequest.Marshal(b, m, deterministic)
}
func (m *CancelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelRequest.Merge(m, src)
}
func (m *CancelRequest) XXX_Size() int {
	return xxx_messageInfo_CancelRequest.Size(m)
}
func (m *CancelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelRequest proto.InternalMessageInfo

func (m *CancelRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CancelRequest) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

type InnerRequest struct {
	CurrencyMark         string   `protobuf:"bytes,1,opt,name=currency_mark,json=currencyMark,proto3" json:"currency_mark,omitempty"`
	CurrencyTradeMark    string   `protobuf:"bytes,2,opt,name=currency_trade_mark,json=currencyTradeMark,proto3" json:"currency_trade_mark,omitempty"`
	Num                  float64  `protobuf:"fixed64,3,opt,name=num,proto3" json:"num,omitempty"`
	Price                float64  `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Cid                  int32    `protobuf:"varint,5,opt,name=cid,proto3" json:"cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InnerRequest) Reset()         { *m = InnerRequest{} }
func (m *InnerRequest) String() string { return proto.CompactTextString(m) }
func (*InnerRequest) ProtoMessage()    {}
func (*InnerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_de98e18bbaa1ad4f, []int{10}
}

func (m *InnerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InnerRequest.Unmarshal(m, b)
}
func (m *InnerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InnerRequest.Marshal(b, m, deterministic)
}
func (m *InnerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InnerRequest.Merge(m, src)
}
func (m *InnerRequest) XXX_Size() int {
	return xxx_messageInfo_InnerRequest.Size(m)
}
func (m *InnerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InnerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InnerRequest proto.InternalMessageInfo

func (m *InnerRequest) GetCurrencyMark() string {
	if m != nil {
		return m.CurrencyMark
	}
	return ""
}

func (m *InnerRequest) GetCurrencyTradeMark() string {
	if m != nil {
		return m.CurrencyTradeMark
	}
	return ""
}

func (m *InnerRequest) GetNum() float64 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *InnerRequest) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *InnerRequest) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

type InnerCancelRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Cid                  int32    `protobuf:"varint,2,opt,name=cid,proto3" json:"cid,omitempty"`
	OrderNo              string   `protobuf:"bytes,3,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InnerCancelRequest) Reset()         { *m = InnerCancelRequest{} }
func (m *InnerCancelRequest) String() string { return proto.CompactTextString(m) }
func (*InnerCancelRequest) ProtoMessage()    {}
func (*InnerCancelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_de98e18bbaa1ad4f, []int{11}
}

func (m *InnerCancelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InnerCancelRequest.Unmarshal(m, b)
}
func (m *InnerCancelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InnerCancelRequest.Marshal(b, m, deterministic)
}
func (m *InnerCancelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InnerCancelRequest.Merge(m, src)
}
func (m *InnerCancelRequest) XXX_Size() int {
	return xxx_messageInfo_InnerCancelRequest.Size(m)
}
func (m *InnerCancelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InnerCancelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InnerCancelRequest proto.InternalMessageInfo

func (m *InnerCancelRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InnerCancelRequest) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *InnerCancelRequest) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func init() {
	proto.RegisterType((*Pair)(nil), "go.micro.api.entrust.Pair")
	proto.RegisterType((*Request)(nil), "go.micro.api.entrust.Request")
	proto.RegisterMapType((map[string]*Pair)(nil), "go.micro.api.entrust.Request.GetEntry")
	proto.RegisterMapType((map[string]*Pair)(nil), "go.micro.api.entrust.Request.HeaderEntry")
	proto.RegisterMapType((map[string]*Pair)(nil), "go.micro.api.entrust.Request.PostEntry")
	proto.RegisterType((*Response)(nil), "go.micro.api.entrust.Response")
	proto.RegisterMapType((map[string]*Pair)(nil), "go.micro.api.entrust.Response.HeaderEntry")
	proto.RegisterType((*TradeRequest)(nil), "go.micro.api.entrust.TradeRequest")
	proto.RegisterType((*TradeOrderResponse)(nil), "go.micro.api.entrust.TradeOrderResponse")
	proto.RegisterType((*TradeOrder)(nil), "go.micro.api.entrust.TradeOrder")
	proto.RegisterType((*UnfinishedRequest)(nil), "go.micro.api.entrust.UnfinishedRequest")
	proto.RegisterType((*BusinessRequest)(nil), "go.micro.api.entrust.BusinessRequest")
	proto.RegisterType((*CurrencyEntrustRequest)(nil), "go.micro.api.entrust.CurrencyEntrustRequest")
	proto.RegisterType((*CancelRequest)(nil), "go.micro.api.entrust.CancelRequest")
	proto.RegisterType((*InnerRequest)(nil), "go.micro.api.entrust.InnerRequest")
	proto.RegisterType((*InnerCancelRequest)(nil), "go.micro.api.entrust.InnerCancelRequest")
}

func init() {
	proto.RegisterFile("proto/entrustsecond/entrustsecond.proto", fileDescriptor_de98e18bbaa1ad4f)
}

var fileDescriptor_de98e18bbaa1ad4f = []byte{
	// 883 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0xcf, 0x6f, 0x1b, 0x45,
	0x14, 0x66, 0x77, 0xfd, 0xf3, 0x39, 0x49, 0xc9, 0x10, 0xa2, 0x6d, 0xa2, 0x96, 0x68, 0x91, 0x68,
	0xe8, 0xc1, 0x54, 0xe1, 0x12, 0x95, 0x13, 0x0e, 0x55, 0xb1, 0x44, 0x43, 0xbb, 0x49, 0x54, 0x0e,
	0x88, 0x68, 0xeb, 0x79, 0x6e, 0x56, 0xf1, 0xee, 0x98, 0x99, 0x59, 0x24, 0x9f, 0xb9, 0x73, 0x83,
	0x1b, 0x7f, 0x00, 0x67, 0xce, 0xfc, 0x21, 0xfc, 0x37, 0x68, 0xde, 0xcc, 0xda, 0x6b, 0x70, 0xad,
	0x48, 0xd9, 0x8a, 0xde, 0x66, 0xde, 0x7c, 0xdf, 0xb7, 0xef, 0xfb, 0xe6, 0xad, 0x7f, 0xc0, 0x83,
	0xa9, 0x14, 0x5a, 0x7c, 0x86, 0xb9, 0x96, 0x85, 0xd2, 0x0a, 0x47, 0x22, 0xe7, 0xcb, 0xbb, 0x3e,
	0x21, 0xd8, 0xce, 0x6b, 0xd1, 0xcf, 0xd2, 0x91, 0x14, 0xfd, 0x64, 0x9a, 0xf6, 0x1d, 0x22, 0x7a,
	0x04, 0x8d, 0xe7, 0x49, 0x2a, 0xd9, 0xfb, 0x10, 0x5c, 0xe3, 0x2c, 0xf4, 0x0e, 0xbc, 0xc3, 0x6e,
	0x6c, 0x96, 0x6c, 0x17, 0x5a, 0x3f, 0x25, 0x93, 0x02, 0x55, 0xe8, 0x1f, 0x04, 0x87, 0xdd, 0xd8,
	0xed, 0xa2, 0x5f, 0x1b, 0xd0, 0x8e, 0xf1, 0xc7, 0x02, 0x95, 0x36, 0x98, 0x0c, 0xf5, 0x95, 0xe0,
	0x8e, 0xe8, 0x76, 0x8c, 0x41, 0x63, 0x9a, 0xe8, 0xab, 0xd0, 0xa7, 0x2a, 0xad, 0xd9, 0x97, 0xd0,
	0xba, 0xc2, 0x84, 0xa3, 0x0c, 0x83, 0x83, 0xe0, 0xb0, 0x77, 0xf4, 0x69, 0x7f, 0x55, 0x43, 0x7d,
	0x27, 0xdd, 0xff, 0x9a, 0xb0, 0x4f, 0x72, 0x2d, 0x67, 0xb1, 0x23, 0xb2, 0x63, 0x08, 0x5e, 0xa3,
	0x0e, 0x1b, 0xc4, 0xff, 0x64, 0x3d, 0xff, 0x29, 0x6a, 0x4b, 0x36, 0x14, 0xf6, 0x05, 0x34, 0xa6,
	0x42, 0xe9, 0xb0, 0x49, 0xd4, 0x07, 0xeb, 0xa9, 0xcf, 0x85, 0x72, 0x5c, 0x22, 0x19, 0x37, 0xaf,
	0x04, 0x9f, 0x85, 0x2d, 0xeb, 0xc6, 0xac, 0x4d, 0x5e, 0x85, 0x9c, 0x84, 0x6d, 0x9b, 0x57, 0x21,
	0x27, 0x7b, 0x17, 0xd0, 0xab, 0xf4, 0xbc, 0x22, 0xd0, 0x47, 0xd0, 0xa4, 0x08, 0x29, 0x95, 0xde,
	0xd1, 0xde, 0xea, 0x26, 0xcc, 0x6d, 0xc4, 0x16, 0xf8, 0xd8, 0x3f, 0xf6, 0xf6, 0x62, 0xe8, 0x94,
	0x56, 0x6a, 0xd3, 0x3c, 0x83, 0xee, 0xdc, 0x63, 0x5d, 0xa2, 0xd1, 0xdf, 0x1e, 0x74, 0x62, 0x54,
	0x53, 0x91, 0x2b, 0x64, 0xf7, 0x01, 0x94, 0x4e, 0x74, 0xa1, 0x4e, 0x04, 0x47, 0xd2, 0x6e, 0xc6,
	0x95, 0x0a, 0x1b, 0xcc, 0x87, 0xc1, 0xa7, 0x1b, 0x79, 0xf8, 0xa6, 0x1b, 0xb1, 0x7a, 0x2b, 0xa7,
	0xa1, 0xbc, 0x96, 0x60, 0x71, 0x2d, 0x6f, 0xe9, 0x12, 0xa2, 0x9f, 0x3d, 0xd8, 0x38, 0x97, 0x09,
	0xc7, 0x72, 0xf0, 0x3f, 0x82, 0xde, 0xa8, 0x90, 0x12, 0xf3, 0xd1, 0xec, 0x32, 0xe5, 0xa5, 0xc1,
	0xb2, 0x34, 0xe4, 0xec, 0x21, 0x6c, 0xcf, 0x01, 0xda, 0x30, 0x0d, 0xcc, 0x27, 0xd8, 0x9d, 0xf2,
	0x80, 0x14, 0x87, 0xdc, 0x74, 0x99, 0x17, 0x19, 0xf9, 0xf0, 0x62, 0xb3, 0x64, 0x3b, 0xd0, 0x9c,
	0xca, 0x74, 0x84, 0x61, 0x83, 0x6a, 0x76, 0x13, 0x9d, 0x02, 0x23, 0xca, 0xb7, 0x92, 0xa3, 0x9c,
	0x47, 0x7d, 0x0c, 0x2d, 0x61, 0x0a, 0x2a, 0xf4, 0x28, 0xca, 0x83, 0xd5, 0x96, 0x2a, 0x4c, 0x87,
	0x8f, 0xfe, 0x08, 0x00, 0x16, 0x65, 0xb6, 0x0f, 0x5d, 0x7b, 0xb0, 0x70, 0xd4, 0xb1, 0x85, 0x21,
	0xb7, 0x86, 0x95, 0x16, 0x19, 0xca, 0x85, 0x13, 0x28, 0x4b, 0x25, 0x60, 0x91, 0x48, 0x70, 0xb3,
	0x44, 0x1a, 0xab, 0x13, 0x99, 0xfb, 0x6f, 0x56, 0xfc, 0x97, 0x39, 0xb5, 0x16, 0x39, 0xed, 0x43,
	0xd7, 0x4a, 0x99, 0x7a, 0x9b, 0xea, 0x1d, 0x2a, 0x9c, 0x16, 0x99, 0x81, 0x8f, 0x11, 0xc3, 0x8e,
	0x85, 0x8f, 0x11, 0xcd, 0xc4, 0xe8, 0xd9, 0x14, 0xc3, 0xae, 0x9d, 0x18, 0xb3, 0x66, 0x77, 0xa1,
	0x93, 0x70, 0x7e, 0xa9, 0xd3, 0x0c, 0x43, 0xa0, 0x7a, 0x3b, 0xe1, 0xfc, 0x3c, 0xcd, 0x90, 0xdd,
	0x03, 0xb0, 0xea, 0x74, 0xd8, 0xa3, 0x43, 0xfb, 0x3c, 0x3a, 0xde, 0x85, 0x96, 0x9d, 0xe8, 0x70,
	0x83, 0x5c, 0xb8, 0x1d, 0xfb, 0x18, 0x36, 0xe7, 0x46, 0xb3, 0x44, 0x5e, 0x87, 0x9b, 0xc4, 0xdc,
	0x28, 0x8b, 0xcf, 0x12, 0x79, 0xcd, 0xfa, 0xf0, 0xc1, 0xbf, 0xd2, 0x20, 0xe8, 0x16, 0x41, 0xb7,
	0x97, 0xf2, 0x30, 0xf8, 0xe8, 0x37, 0x0f, 0xb6, 0x2f, 0xf2, 0x71, 0x9a, 0xa7, 0xea, 0x0a, 0x79,
	0x39, 0x86, 0xff, 0x79, 0x94, 0x77, 0xf3, 0x47, 0xf9, 0x6f, 0x78, 0x94, 0x09, 0x7f, 0x92, 0x66,
	0xa9, 0x76, 0x77, 0x68, 0x37, 0xc6, 0xad, 0x18, 0x8f, 0x15, 0x7d, 0xfc, 0x92, 0x5b, 0xbb, 0x8b,
	0x7e, 0xf1, 0xe0, 0xce, 0xa0, 0x50, 0x69, 0x8e, 0x4a, 0xbd, 0xd5, 0xb6, 0x6e, 0xfa, 0x96, 0xfc,
	0xe9, 0xc1, 0xee, 0x89, 0x63, 0x3f, 0xb1, 0xc3, 0xff, 0xee, 0xc4, 0x55, 0x19, 0x9a, 0x66, 0x75,
	0x68, 0xa2, 0xc7, 0xb0, 0x79, 0x92, 0xe4, 0x23, 0x9c, 0x94, 0xbd, 0x6e, 0x81, 0x3f, 0x7f, 0x0d,
	0xfd, 0x94, 0x9b, 0x39, 0xa5, 0x97, 0xf1, 0x32, 0x17, 0xae, 0x97, 0x36, 0xed, 0x4f, 0x45, 0xf4,
	0xbb, 0x07, 0x1b, 0xc3, 0x3c, 0x37, 0x9f, 0x09, 0xff, 0x7f, 0xfe, 0x06, 0x37, 0x4a, 0xb9, 0xb3,
	0x67, 0x96, 0xd1, 0x0b, 0x60, 0xd4, 0xde, 0x7a, 0x83, 0x8e, 0xe7, 0xcf, 0x79, 0x4b, 0x96, 0x83,
	0x25, 0xcb, 0x47, 0x7f, 0xb5, 0xa1, 0xed, 0x2e, 0x97, 0x0d, 0xa1, 0x65, 0x95, 0xd9, 0xbd, 0xb5,
	0xdf, 0xeb, 0x7b, 0xf7, 0xd7, 0x7f, 0xc9, 0x44, 0xef, 0xb1, 0x97, 0xb0, 0xf3, 0x14, 0xf5, 0xe2,
	0x3d, 0x1b, 0x14, 0xb3, 0x6f, 0x52, 0xa5, 0x6f, 0x2f, 0xfc, 0x1d, 0x7c, 0xb8, 0x24, 0x7c, 0x86,
	0x93, 0x49, 0x3d, 0xca, 0xcf, 0x00, 0x5c, 0x10, 0x83, 0x62, 0x76, 0x7b, 0xb9, 0x53, 0xe8, 0x39,
	0x39, 0xd3, 0xe2, 0xed, 0xf5, 0x5e, 0xc0, 0x96, 0xfb, 0xf9, 0x52, 0x28, 0x5d, 0x8f, 0xe3, 0x73,
	0xd8, 0xa6, 0x71, 0x1a, 0x14, 0xb3, 0x33, 0xfa, 0x81, 0x9b, 0xc8, 0x1a, 0x8c, 0x5f, 0xb8, 0x21,
	0x35, 0xb6, 0x6b, 0x94, 0x7d, 0x09, 0x3b, 0x95, 0xd9, 0xaf, 0x51, 0xf8, 0x7b, 0xb8, 0x4b, 0xc2,
	0x95, 0x68, 0x6b, 0x54, 0xff, 0x01, 0xf6, 0xab, 0xea, 0x5f, 0xa1, 0x4e, 0xd2, 0x1a, 0xbb, 0x7f,
	0xd5, 0xa2, 0xff, 0x24, 0x9f, 0xff, 0x13, 0x00, 0x00, 0xff, 0xff, 0x3f, 0x38, 0x86, 0x4e, 0xbe,
	0x0c, 0x00, 0x00,
}
